# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - "main"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  buildx:
    runs-on: ubuntu-latest
   
    steps:

    - uses: actions/checkout@v4
    - name: Use Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install

    - name: Lint code
      run: npm run prettier:check

    - name: Debug Secrets
      run: |
        echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
        echo "DOCKER_PASSWORD length: ${#DOCKER_PASSWORD}" 

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t danyloberk/lab45:latest .

    - name: Push Docker image
      run: docker push danyloberk/lab45:latest
