name: Destroy Terraform resources

on:
  workflow_dispatch:

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_ami: ${{ secrets.AMI }}
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_PRIVATE_KEY }}
      TF_VAR_key_name: connection_key
      
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_PRIVATE_KEY }}
        aws-region: eu-north-1
      
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2
      
    - name: Terraform init and destroy
      run: |
        echo `pwd`
      
        echo "** Running Terraform Destroy**"
        terraform destroy -auto-approve
      working-directory: ./